---

        
- name: install httpd
  apt: name=apache2 state=present

- name: Copy file from local to remote
  copy: src=index.html dest=/var/www/html/index.html mode=0755

- name: service apache2
  service: name=apache2 state=started enabled=yes

- name: wait for httpd port to start
  wait_for: port=80

